CREATE SCHEMA IF NOT EXISTS BASEPROJECT_DM_TABLES;

create table baseproject_dm_tables.CATEGORIES (
   identifier varchar(255) not null,
    description varchar(255),
    primary key (identifier)
);

create table baseproject_dm_tables.PRODUCT_SIZES (
   identifier varchar(255) generated by default as identity,
    size varchar(255),
    value integer,
    productJpa varchar(255) not null,
    primary key (identifier)
)

create table baseproject_dm_tables.PRODUCTS (
   uuid varchar(255) not null,
    description varchar(255),
    productIdentifier varchar(255),
    categoryJpa_id varchar(255) not null,
    primary key (uuid)
);

create table baseproject_dm_tables.SUPPLIERS (
   uuid varchar(255) not null,
    companyName varchar(255),
    country varchar(255),
    primary key (uuid)
);

create table baseproject_dm_tables.USERS (
   email varchar(255) not null,
    name varchar(255),
    password varchar(255),
    surname varchar(255),
    userRights varchar(255),
    primary key (email)
);

alter table baseproject_dm_tables.PRODUCT_SIZES add constraint FK_PRODUCTSIZE_PRODUCT_IDENTIFIER
   foreign key (productJpa) references baseproject_dm_tables.PRODUCTS;


alter table baseproject_dm_tables.PRODUCTS add constraint FK_PRODUCT_CATEGORY
   foreign key (categoryJpa_id) references baseproject_dm_tables.CATEGORIES;



